import 'bootstrap/dist/css/bootstrap.css';
import './globals.sass'

export const metadata = {
  title: 'Todolist App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt_BR">
      <body>{children}</body>
    </html>
  )
}
